### ISSUE TITLE
When pressing Q (Quit) on some pages, it will move to the page bottom

### ISSUE THREAD

**Issue by Pathduck** [Pathduck/spatialnavigation#12]
It's been like this since the start: On some pages pressing Q will move focus down to the bottom of the page.

If a fix could be found for that it would be really great. I kind of suspect this might be in the "black box" library code and if so might be really hard to figure out.

Example page it happens every time:
https://www.nrk.no

**Comment by ortiza5** [comment]
I will look into it. Thanks for finding a page that can be used for testing.

**Comment by Pathduck** [comment]
Some more random findings that might help:

Basically, any key can act as "Quit" as long as it's not in `var keys`.

In the `markTarget` function:
```
default:
    unselect();
```

In the old `switch (event.keyCode)` the keycode for Q (81) would return a 10. But 10 doesn't actually do anything in `markTarget` so it just defaults to `unselect()` ... but any other key would do the same😄 

`unselect()` just seems to go to `undisplayUrl()` which again does a:
`display.remove();`
Which is *probably* what might trigger the behaviour?

It's very confusing. I've always thought it logical that Q should "quit" out of the expand/contract mode. But apparently ESC works for that. Pressing Q however does quit out of "spatial nav. mode", i.e. returns the page to no nav focus, which I honestly have never seen a big use for. 

The best case would I think be if Q would exit out of *both* spatial nav and expand/contract modes.

Figuring this code is somewhat like trying to find out the use of the [Antikythera Mechanism](https://en.wikipedia.org/wiki/Antikythera_mechanism) 😆

**Comment by ortiza5** [comment]
It is too bad there wasn't a [Clickspring](https://www.youtube.com/channel/UCworsKCR-Sx6R6-BnIjS2MA) video for me to watch to try and get a better understanding of this bug.

I will commit a potential fix soon.

Don't ask me why or how it works. Guess the Antikythera Mechanism is an apt analogue for this code.

---

I narrowed down one line, that if I commented it out, the scroll wouldn't happen. But it caused a bunch of old `input` elements to be added to the end of the `body` element since the line was responsible for removing the `input`.

I then tried removing the `input` with the devTools console, and the scroll didn't happen!!! That gave me a very very very wrong terrible hacky idea for what might fix it.

So I threw a timer around it and it seems to work...😵

From this: `observer.remove();`
To this: `setTimeout(function () { return observer.remove(); }, 1);`

Give it a try and let me know if it works for you as well. Just want to make sure my computer didn't decide to trick me into believing I found a fix😅

**Comment by Pathduck** [comment]
Brilliant - it does seem to work! 👍 
Q (and Esc) still works to quit out of spat.nav. mode as well.

It does seem kind of "hacky" but I really have no idea what a `setTimeout` does in the context of JS. It wouldn't have any (major) performance issues?

**Comment by ortiza5** [comment]
All the `setTimeout` is doing, to the best of my knowledge, is is delaying the running of that code by 1 millisecond.

Don't think it should cause any noticeable performance issues. I started out with the timer set to a full second, but I kept lowering it and the scroll never came back, so I left it at 1ms.

Wish I had taken a class with `JavaScript` in college. Might have learned some of the inner workings better.

**Comment by Pathduck** [comment]
@ortiza5 
> Wish I had taken a class with JavaScript in college. Might have learned some of the inner workings better.

When I went to Uni, JavaScript wasn't even an option. It was a joke, used for fancy cursors and snow-falling effects. Everybody who were into web dev hated it, it slowed everything down. Server-side processing like PHP and CGI/Perl was the thing to learn...

But yeah wish I'd paid attention in later years as JS grew into a mature language and now can do some amazing things. It's still a pretty clunky language though 😆

**Comment by ortiza5** [comment]
Yeah, JS is still looked down on as far as languages go.

Heard lots of jokes about it through the various classes. Especially in a Programming Languages course where they forced us to use those elegantly minimal languages that are awful to use like Prolog, (((((Scheme/Lisp)))))(so many parentheses), and Haskell.

What did you study in Uni and learn afterward? Got to know what I can pester you about since I don't have much experience with web technology 😁

**Comment by Pathduck** [comment]
> What did you study in Uni and learn afterward?

I studied computer networks and programming in Java, C/C++, Databases and some web stuff. I've learned most of what I know of HTML/CSS and (a little) PHP/Perl later. 

At my last job I actually did a little bit Javascript programming, it was mostly linear scripting tasks, and not actually JS but more like an ancient version of ECMAscript.

> I don't have much experience with web technology 😁

You seem to do just fine :)
