### ISSUE TITLE
Bug with closing tabs using `Ctrl+W`

### ISSUE THREAD

**Issue by Pathduck** [Pathduck/spatialnavigation#13]
For some reason I've only noticed this now. But when using `Ctrl+W` to close several tabs in one go the extensions seems to interfere with it, forcing you to release the Ctrl for every tab and pressing W again.

To reproduce it just open a bunch of tabs, move to the last one and try pressing `Ctrl+W` several times. With the older/default extension and without the extension tabs will close as expected but with this version it doesn't seem to handle Ctrl being held down.

@ortiza5 if you can find the time to look into it, it would be great. Not sure my understanding of the code will be much help here... but no rush really, it's not a major issue.

**Comment by ortiza5** [comment]
I have some idea about why it is happening, but I don't know why it should interfere with the browser keyboard shortcut of `Ctrl+W`.

The newly active tab after one is closed doesn't know that `Ctrl` is being pressed when it becomes active, so it is just seeing `W` get pressed. Since `W` is a keyboard shortcut for a command, the new tab is executing it. That is somehow preventing the browser's shortcut.

I will see if there is some way to detect keys being held down when a window gains focus.

**Comment by ortiza5** [comment]
This seems to solve the issue at least temporarily, but I think the content scripts in each tab should be able to pass along any keys that are being pressed with message passing.
